apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: kserve-tensorflow-serving
spec:
  containers:
  - args:
    - --model_name={{"{{"}}.Name{{"}}"}}
    - --port=9000
    - --rest_api_port=8080
    - --model_base_path=/mnt/models
    - --rest_api_timeout_in_ms=60000
    command:
    - /usr/bin/tensorflow_model_server
    image: tensorflow/serving:2.13.0
    name: kserve-container
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 2Gi
  supportedModelFormats:
  - autoSelect: true
    name: {{ .Values.modelFormat }}
    version: "1"
  - autoSelect: true
    name: {{ .Values.modelFormat }}
    version: "2"
